---
- hosts: test
  become: true
  tasks:
  - name: Removing root qdisc
    shell: "tc qdisc del dev eth0 root || true"
    # we always restart

  - name: Preparing htb
    shell: "tc qdisc add dev eth0 root handle 1: htb"
    when: 
      - "{{ tc.enable }}"
      - "'b' in tc.mode"

  - name: Add rate limit
    command: "tc class add dev eth0 parent 1: classid 1:{{ (item.0 + 1) * 10  }} htb rate {{ item.1.rate }}"
    with_indexed_items: "{{ tc.constraints }}"
    when:
      - "{{ tc.enable }}"
      - item[1].source == ansible_eth0["ipv4"]["address"]
      - "'b' in tc.mode"


  - name: Adding delay
    command: "tc qdisc add dev eth0 parent 1:{{ (item.0 + 1) * 10 }} handle {{ (item.0 + 1)*10 }}: netem delay {{ item.1.delay }}"
    with_indexed_items: "{{ tc.constraints }}"
    when:
      - "{{ tc.enable }}"
      - item[1].source == ansible_eth0["ipv4"]["address"]
      - "'b' in tc.mode"
      - "'l' in tc.mode"

  - name: Adding delay
    command: "tc qdisc add dev eth0 parent 1: handle {{ (item.0 + 1)*10 }}: netem delay {{ item.1.delay }}"
    with_indexed_items: "{{ tc.constraints }}"
    when:
      - "{{ tc.enable }}"
      - item[1].source == ansible_eth0["ipv4"]["address"]
      - "'b' not in tc.mode" 
      - "'l' in tc.mode"


  - name: Adding filter
    command: "tc filter add dev eth0  parent 1: protocol ip  u32 match ip dst {{ item.1.target }} flowid 1:{{ (item.0 + 1) * 10 }}"
    with_indexed_items: "{{ tc.constraints }}"
    when:
      - "{{ tc.enable }}"
      - item[1].source == ansible_eth0["ipv4"]["address"]
      - "'bl' in tc.mode"

